version: '3.3'

services:
  web:
    build: 
      context: ./mainapp
      dockerfile: Dockerfile.prod
    command: gunicorn trendspotter.wsgi:application --bind 0.0.0.0:8000  --timeout 400
    volumes:
      - ./mainapp/:/usr/src/mainapp/
      - static_volume:/home/mainapp/web/staticfiles
      - user_files:/tmp
    expose:
      - 8000
    env_file:
      - ./.env.prod
    stdin_open: true

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/mainapp/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  static_volume:
  user_files:

