version: '3.8'

services:
  web:
    build: ./mainapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mainapp/:/usr/src/mainapp/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    stdin_open: true
    networks:
      - postgres
  db:
    image: postgres:12.0-alpine
    volumes:
      - keepdataa:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    volumes:
       - pgadmin:/root/.pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    
volumes:
  keepdataa:
  pgadmin:


