version: '3.3'

services:
  web:
    build: 
      context: ./mainapp
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mainapp/:/usr/src/mainapp/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    stdin_open: true
    networks:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:

