# Generated by Django 3.0.7 on 2020-12-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mert3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mert3',
        ),
    ]
