# Generated by Django 3.0.7 on 2021-01-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor_NLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(blank=True, max_length=10000, null=True)),
                ('preproc', models.CharField(blank=True, max_length=10000, null=True)),
                ('nlp', models.CharField(blank=True, max_length=10000, null=True)),
                ('stopwords', models.TextField(blank=True, null=True)),
                ('corrections', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
