# Generated by Django 3.0.7 on 2021-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_remove_processor_nlp_nlp'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor_nlp',
            name='nlp',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
