# Generated by Django 3.0.7 on 2020-12-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200)),
                ('mention', models.CharField(max_length=200)),
                ('from_user', models.CharField(max_length=100)),
                ('to_user', models.CharField(max_length=100)),
                ('retweets_of', models.CharField(max_length=200)),
                ('conversation_id', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('specific_url', models.CharField(max_length=200)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_quote', models.BooleanField(default=False)),
                ('has_hashtag', models.BooleanField(default=False)),
                ('has_links', models.BooleanField(default=False)),
                ('han_mention', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('has_videos', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
