# Generated by Django 3.0.7 on 2020-12-17 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='context',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='han_mention',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='has_hashtag',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='has_images',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='has_links',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='has_videos',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='is_quote',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='is_retweet',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='retweets_of',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='specific_url',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='to_user',
        ),
        migrations.AddField(
            model_name='tracker',
            name='frequency_level1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='frequency_level2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='max_tweet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='query',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
