# Generated by Django 3.0.7 on 2020-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201217_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='fetch_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
