# Generated by Django 3.0.7 on 2020-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker_fetch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('lang', models.CharField(max_length=20)),
                ('conversation_id', models.CharField(max_length=100)),
                ('possibly_sensitive', models.BooleanField()),
                ('in_reply_to_user_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('withheld', models.BooleanField()),
                ('place_place_full_name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100)),
                ('place_country', models.CharField(max_length=100)),
                ('place_country_code', models.CharField(max_length=100)),
                ('place_place_name', models.CharField(max_length=100)),
                ('place_place_type', models.CharField(max_length=100)),
                ('key', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('to_id', models.CharField(max_length=100)),
                ('key', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferencedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('lang', models.CharField(max_length=20)),
                ('conversation_id', models.CharField(max_length=100)),
                ('possibly_sensitive', models.BooleanField()),
                ('in_reply_to_user_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('withheld', models.BooleanField()),
                ('place_place_full_name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100)),
                ('place_country', models.CharField(max_length=100)),
                ('place_country_code', models.CharField(max_length=100)),
                ('place_place_name', models.CharField(max_length=100)),
                ('place_place_type', models.CharField(max_length=100)),
                ('key', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('protected', models.BooleanField()),
                ('url', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
                ('followers_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('tweet_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('key', models.DateTimeField()),
            ],
        ),
    ]
