# Generated by Django 3.0.7 on 2020-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_collectedtweets_reference_referencedtweets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedtweets',
            name='conversation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='in_reply_to_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_country_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_place_full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_place_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='place_place_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='possibly_sensitive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='quote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='reply_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='withheld',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='conversation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='in_reply_to_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_country_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_place_full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_place_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='place_place_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='possibly_sensitive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='quote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='reply_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='withheld',
            field=models.BooleanField(null=True),
        ),
    ]
