# Generated by Django 3.0.7 on 2020-12-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201220_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
