# Generated by Django 3.0.7 on 2020-12-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201220_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedtweets',
            name='possibly_sensitive',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collectedtweets',
            name='withheld',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='possibly_sensitive',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='referencedtweets',
            name='withheld',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
