# Generated by Django 3.0.7 on 2020-12-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201220_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectedtweets',
            options={'managed': False},
        ),
    ]
