# Generated by Django 3.0.7 on 2020-12-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20201220_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collectedtweets',
            table='TWEETS_MANUAL',
        ),
    ]
