# Generated by Django 3.0.7 on 2020-12-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20201221_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('lang', models.CharField(max_length=20)),
                ('conversation_id', models.CharField(max_length=100, null=True)),
                ('possibly_sensitive', models.CharField(max_length=10, null=True)),
                ('in_reply_to_user_id', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('reply_count', models.IntegerField(null=True)),
                ('like_count', models.IntegerField(null=True)),
                ('quote_count', models.IntegerField(null=True)),
                ('withheld', models.CharField(max_length=100, null=True)),
                ('place_place_full_name', models.CharField(max_length=100, null=True)),
                ('place_id', models.CharField(max_length=100, null=True)),
                ('place_country', models.CharField(max_length=100, null=True)),
                ('place_country_code', models.CharField(max_length=100, null=True)),
                ('place_place_name', models.CharField(max_length=100, null=True)),
                ('place_place_type', models.CharField(max_length=100, null=True)),
                ('key', models.DateTimeField()),
            ],
            options={
                'db_table': 'TWEETS_MANUAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferencedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('lang', models.CharField(max_length=20)),
                ('conversation_id', models.CharField(max_length=100, null=True)),
                ('possibly_sensitive', models.CharField(max_length=10, null=True)),
                ('in_reply_to_user_id', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('reply_count', models.IntegerField(null=True)),
                ('like_count', models.IntegerField(null=True)),
                ('quote_count', models.IntegerField(null=True)),
                ('withheld', models.CharField(max_length=100, null=True)),
                ('place_place_full_name', models.CharField(max_length=100, null=True)),
                ('place_id', models.CharField(max_length=100, null=True)),
                ('place_country', models.CharField(max_length=100, null=True)),
                ('place_country_code', models.CharField(max_length=100, null=True)),
                ('place_place_name', models.CharField(max_length=100, null=True)),
                ('place_place_type', models.CharField(max_length=100, null=True)),
                ('key', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TweetAnnotation',
        ),
        migrations.DeleteModel(
            name='TweetAnnotationDomain',
        ),
        migrations.DeleteModel(
            name='TweetAnnotationEntity',
        ),
        migrations.DeleteModel(
            name='TweetEntity',
        ),
        migrations.DeleteModel(
            name='TweetInfo',
        ),
        migrations.DeleteModel(
            name='TweetMedia',
        ),
        migrations.DeleteModel(
            name='TweetReferenced',
        ),
        migrations.DeleteModel(
            name='TweetReferencedInfo',
        ),
        migrations.DeleteModel(
            name='TweetUser',
        ),
    ]
