# Generated by Django 3.0.7 on 2021-01-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20201223_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetAnnotation',
        ),
        migrations.DeleteModel(
            name='TweetAnnotationDomain',
        ),
        migrations.DeleteModel(
            name='TweetAnnotationEntity',
        ),
        migrations.DeleteModel(
            name='TweetEntity',
        ),
        migrations.DeleteModel(
            name='TweetInfo',
        ),
        migrations.DeleteModel(
            name='TweetMedia',
        ),
        migrations.DeleteModel(
            name='TweetReferenced',
        ),
        migrations.DeleteModel(
            name='TweetReferencedInfo',
        ),
        migrations.DeleteModel(
            name='TweetUser',
        ),
    ]
