# Generated by Django 3.0.7 on 2021-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_tracker_query_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='max_tweet_id',
        ),
        migrations.AddField(
            model_name='tracker',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
